import { PostPerformance } from "@/types/analytics";
import { PersonaProfile, ScheduledJob } from "@/types/scheduler";

export const initialPersonas: PersonaProfile[] = [
  {
    id: "persona_alex_tech",
    name: "Alex V - The AI Maverick",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    niche: "AI Engineering & Tech Breakdown",
    defaultTone: "Technical, fast-paced, high-conviction",
    pacingWpm: 165,
    energyLevel: "high_energy",
    framingStyle: "Tight framing with subtle camera pan & neon rim lighting",
    voiceStyle: "Deep, crisp studio resonance",
  },
  {
    id: "persona_maya_growth",
    name: "Maya Vance - Growth Strategist",
    avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    niche: "Creator Monetization & Viral Ops",
    defaultTone: "Direct, analytical, actionable, sharp",
    pacingWpm: 155,
    energyLevel: "conversational",
    framingStyle: "Clean minimalist desk setup with pop-up telemetry charts",
    voiceStyle: "Energetic, clear articulate delivery",
  },
  {
    id: "persona_kai_crypto",
    name: "Kai Thorne - Deep Alpha Trader",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    niche: "DeFi & Macro Market Trends",
    defaultTone: "Unfiltered, urgency-driven, contrarian",
    pacingWpm: 180,
    energyLevel: "electrifying",
    framingStyle: "Dynamic handheld close-up with Bloomberg terminal backdrop",
    voiceStyle: "Fast, punchy, aggressive modulation",
  },
];

export const samplePosts: PostPerformance[] = [
  {
    id: "post_ugc_01",
    title: "Why 99% of LLM wrappers will die in 6 months",
    platform: "tiktok",
    thumbnailUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&auto=format&fit=crop&q=80",
    publishedAt: "2026-08-16T14:30:00Z",
    views: 48920,
    watchTimeSeconds: 11.4,
    retention3s: 36.2, // Critical dropoff
    ctr: 2.1,
    engagementRate: 4.8,
    currentHook: "Hey guys, today I want to talk about why most AI startups are making a huge mistake with their wrappers...",
    currentHookType: "statement",
    personaSettings: {
      name: "Alex V - The AI Maverick",
      pacingWpm: 145,
      tone: "Explanatory, casual introduction",
      energyLevel: "conversational",
      framing: "Medium shot with static background",
    },
    retentionCurve: [
      { second: 0, retentionRate: 100 },
      { second: 1, retentionRate: 72 },
      { second: 2, retentionRate: 51 },
      { second: 3, retentionRate: 36.2, isDropoffSpike: true, note: "Crucial drop-off: Generic intro creates high swipe-away" },
      { second: 5, retentionRate: 28 },
      { second: 8, retentionRate: 22 },
      { second: 12, retentionRate: 18 },
      { second: 16, retentionRate: 15 },
      { second: 20, retentionRate: 13.5 },
    ],
  },
  {
    id: "post_ugc_02",
    title: "The $10k/mo Autonomous Content Farm Architecture",
    platform: "youtube",
    thumbnailUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&auto=format&fit=crop&q=80",
    publishedAt: "2026-08-17T18:00:00Z",
    views: 124500,
    watchTimeSeconds: 24.8,
    retention3s: 64.5, // Stronger performance
    ctr: 5.4,
    engagementRate: 8.9,
    currentHook: "If you are still editing TikToks manually in CapCut, you are losing 40 hours every single week.",
    currentHookType: "shock_value",
    personaSettings: {
      name: "Maya Vance - Growth Strategist",
      pacingWpm: 165,
      tone: "Authoritative, fast, high contrast",
      energyLevel: "high_energy",
      framing: "Dynamic macro crop with kinetic subtitles",
    },
    retentionCurve: [
      { second: 0, retentionRate: 100 },
      { second: 1, retentionRate: 89 },
      { second: 2, retentionRate: 76 },
      { second: 3, retentionRate: 64.5, note: "Strong hook holds early crowd" },
      { second: 5, retentionRate: 58 },
      { second: 8, retentionRate: 52 },
      { second: 12, retentionRate: 46 },
      { second: 16, retentionRate: 41, isDropoffSpike: true, note: "Mid-video explanation dragged without code screen-share" },
      { second: 20, retentionRate: 35 },
    ],
  },
  {
    id: "post_ugc_03",
    title: "Instagram Algorithm Secret: The 3.2s Loop Mechanism",
    platform: "instagram",
    thumbnailUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400&auto=format&fit=crop&q=80",
    publishedAt: "2026-08-18T09:15:00Z",
    views: 82140,
    watchTimeSeconds: 8.2,
    retention3s: 41.0,
    ctr: 3.2,
    engagementRate: 6.1,
    currentHook: "Did you notice that every viral Reel this week ends with the exact same visual cue?",
    currentHookType: "question",
    personaSettings: {
      name: "Kai Thorne - Deep Alpha Trader",
      pacingWpm: 150,
      tone: "Curious, conspiratorial",
      energyLevel: "conversational",
      framing: "Extreme close up, subtle lens flare",
    },
    retentionCurve: [
      { second: 0, retentionRate: 100 },
      { second: 1, retentionRate: 79 },
      { second: 2, retentionRate: 58 },
      { second: 3, retentionRate: 41.0, isDropoffSpike: true, note: "Question was too abstract without on-screen visual proof" },
      { second: 5, retentionRate: 33 },
      { second: 8, retentionRate: 26 },
      { second: 12, retentionRate: 21 },
    ],
  },
];

export const sampleInitialJobs: ScheduledJob[] = [
  {
    jobId: "job_synth_8921",
    payload: {
      contentTitle: "3 AI Agents That Run an Entire E-Com Store",
      openingHook: "Stop hiring $3,000/mo agencies: these three open-source agents do the exact same work in 4 minutes.",
      scriptContent: "Scene 1: Persona points at screen showing agentic loop.\nScene 2: Agent 1 does product research.\nScene 3: Agent 2 writes 100 ad copy variants.\nScene 4: Agent 3 launches Facebook ads autonomously.",
      personaId: "persona_alex_tech",
      personaSettings: {
        name: "Alex V - The AI Maverick",
        tone: "Fast, authoritative, high-energy",
        pacingWpm: 185,
        energyLevel: "high_energy",
        framing: "Tight dynamic crop with kinetic subtitles",
      },
      targetPlatforms: [
        { channel: "tiktok", enabled: true, aspectRatio: "9:16", autoHashtags: true, privacy: "public" },
        { channel: "instagram", enabled: true, aspectRatio: "9:16", autoHashtags: true, privacy: "public" },
        { channel: "youtube", enabled: true, aspectRatio: "9:16", autoHashtags: true, privacy: "public" },
      ],
      scheduledTimestamp: new Date(Date.now() + 3600 * 4000).toISOString(),
      tags: ["ai", "automation", "growth", "entrepreneurship"],
      callToAction: "Comment 'AGENT' and I'll send you the complete GitHub repo and workflow architecture.",
    },
    status: "PROCESSING",
    createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    scheduledFor: new Date(Date.now() + 3600 * 4000).toISOString(),
    stages: [
      { id: "s1", name: "Payload Validation", description: "Enforcing character limits & schema contracts", status: "COMPLETED", progressPercent: 100 },
      { id: "s2", name: "UGC Prompt Synthesis", description: "Translating script into diffusion keyframes & pacing markers", status: "COMPLETED", progressPercent: 100 },
      { id: "s3", name: "Voice & Avatar Engine", description: "Synthesizing voice audio at 185 WPM with lip-sync generation", status: "PROCESSING", progressPercent: 68 },
      { id: "s4", name: "Dynamic Subtitles & B-Roll", description: "Baking kinetic captions, sound effects, and color grading", status: "PENDING", progressPercent: 0 },
      { id: "s5", name: "Cross-Platform Dispatch", description: "Multi-bitrate encoding and staging for TikTok/IG/YT APIs", status: "PENDING", progressPercent: 0 },
    ],
  },
];
